export const styles = ({
  accordion: {
    width: "722px",
    height: "60px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  loginCard: {
    marginTop: "158px",
    width: "520px",
    padding: "62px",
    background: "#F8F8F8 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    opacity: 1,
  },
  loginText: {
    marginBottom: "51px",
    // textAlign: "center",
    font: "normal normal 600 16px/22px Nunito Sans",
    letterSpacing: "0px",
    color: "#E87C23",
    textTransform: "uppercase",
    opacity: 1,
  },
  card: {
    width: "267px",
    height: "321px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "2px solid #DDDDDD",
    borderRadius: "6px",
    opacity: 1,
  },
  submitButton: {
    width: "397px",
    height: "60px",
    background: "#080730 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
    textAlign: "center",
    font: "normal normal 600 14px/19px Nunito Sans",
    letterSpacing: "0px",
    color: "#FFFFFF",
  },
  uploadButton: {
    width: "158px",
    height: "60px",
    background: "#080730 0% 0% no-repeat padding-box",
    borderRadius: "4px",
    opacity: 1,
  },
  discardButton: {
    width: "158px",
    height: "60px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  label: {
    marginTop: "24px",
    marginBottom: "10px",
    textAlign: "left",
    font: "normal normal 600 12px/16px Nunito Sans",
    letterSpacing: "0px",
    color: "#5B5B5B",
    opacity: 1,
  },
  pendingButton: {
    width: "121px",
    height: "40px",
    background: "#F0C11B 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  cancelButton: {},
  editButton: {
    width: "67px",
    height: "40px",
    background: "#E87C23 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  activeButton: {
    width: "121px",
    height: "40px",
    background: "#24A047 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1
  },
  resetPasswordButton: {
    width: "145px",
    height: "40px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  modal: {
    width: "377px",
    height: "529px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    opacity: 1,
  },
  layout: {
    height: "100vh",
    background: "#F8F8F8 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    opacity: 1,
  },
  header: {
    borderBottom: "1px solid #DDDDDD",
    padding: "30px"
  },
  dashboardInput: {
    width: "329px",
    height: "60px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  searchIcon: {
    width: "329px",
    height: "60px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  loginInput: {
    width: "397px",
    height: "60px",
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #DDDDDD",
    borderRadius: "4px",
    opacity: 1,
  },
  passwordResetText: {
    marginTop: "75px",
    textAlign: "left",
    font: "normal normal 600 14px/19px Nunito Sans",
    letterSpacing: "0px",
    color: "#5B5B5B",
    opacity: 1,
  },
  spanText: {
    textAlign: "left",
    font: "normal normal bold 14px/19px Nunito Sans",
    letterSpacing: "0px",
    color: "#E87C23",
    opacity: 1,
    cursor: "pointer",
  },
  sidebarIcon: {
    marginLeft: "82px",
    marginRight: "27px",
    width: "22px",
    height: "17px",
    color: "#FFFFFF",
    opacity: 1,
  },
  innerSidebar: {
    borderRight: "1px solid #DDDDDD",
    height: "91vh"
  },
  innerSidebarHeader: {
    borderBottom: "1px solid #DDDDDD",
    padding: "40px",
    width: "280px",
    textAlign: "left",
    font: "normal normal bold 16px/22px Nunito Sans",
    letterSpacing: "0px",
    color: "#080730",
    opacity: 1,
  },
  logo: {
    marginBottom: "78px",
  }
})